[Interface]
PrivateKey = 6J4RCv/oRUsadR48fGYVyg+QpSuada5FfT7P4v2EnGg=
Address = 10.0.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enp3s0 -j MASQUERADE
[Peer]
PublicKey = SuVrYdMu2Y3FhlT2WVvg0KlT34MKKQ0ZHPDu6/Ry8nQ=
AllowedIPs = 10.0.0.2/32
